title: "Lena Merker"
baseURL: "https://lenamerker.de/"
languageCode: "de"

metaDataFormat: "yaml"
defaultContentLanguage: "de"
enableRobotsTXT: true
disableKinds:
  - taxonomies
  - taxonomyTerm

sitemap:
  changeFreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  env: production
